#origin commit: 523ebed5e9ab737acd4fac6c805313d723900976
# this file is a template for valued configuration file
# use this command to generate src/config.yml before running the webapp (yarn start)
#
# `npm run genconfig`
#
# src/config.yml file isn't tracked by git, you can use standard or development version

## build version
version: '${npm_package_version}'
#

## switch styles sass
# theme: 'default'
theme: '${JOURNEY_THEME}'
# theme: 'red'

##base url for static contents(html, pngs, json)
staticBaseUrl: '${STATIC_BASEURL}'

# Default OTP API
api:
  host: ${API_HOST}
  path: ${API_PATH}
  port: ${API_PORT}

#overwrite default values by theme
configByTheme:
  red:
    map:
      overlays:
        - name: drt
          enabled: false
        - name: webcam
          # visible: false
          enabled: true
        - name: vms
          enabled: true
          # visible: false
    footer:
      enabled: true
      navList:
        - name: acessibility
          enabled: true
          type: link
          linkUrl : ""
        - name: legals
          enabled: true
          type: link
          linkUrl : ""
        - name: credits
          enabled: true
          type: link-modal
          htmlUrl: "/static/credits.html"
        - name: privacy policy
          enabled: true
          type: link
          linkUrl : ""
        - name: meteo
          enabled: true
          type: link
          linkUrl : ""
      # - name: modal testuale di test
      #   enabled: true
      #   type: modal
      #   text: contenuto del modal testuale di test

branding: "Merano - Alto Adige/Suedtirol"
title: "Merano - Alto Adige/Suedtirol"
brandNavbar: Merano
brandNavbarLogo: null

## overwrite default values by location.hostname
brandByDomain:
  localhost:
    branding: Journey
    title: Journey
    brandNavbar: Journey
    brandNavbarLogo: openmove

configByDomain:
  localhost:
    map:
      initLat: 46.225787
      initLon: 10.826701

reportIssue:
  mailto: support@openmove.com

#TODO check for configByDomain
analytics:
  matomo:
    baseUrl: ${MATOMO_BASE_URL}
    siteId: ${MATOMO_SITE_ID}
  # google:
  #   globalSiteTag: ${GOOGLE_ANALYTICS_ID}

header:
  enabled: true
  navList:
  - name: ""
    type: nav-item
    enabled: true
    icon: "location-arrow"
    #TODO icon: "location-crosshairs" #new fotawesome
    onClickEvent: setGpsLocation
  - name: route_viewer
    type: nav-item
    enabled: true
    icon: "bus"
    onClickEvent: showRouteViewer
  - name: restart
    type: nav-item
    enabled: true
    icon: "undo"
    onClickEvent: startOver
  - name: credits
    type: nav-modal
    htmlUrl: "/static/credits.html"
    enabled: true
    icon: "info-circle"
  - name: language-dropdown
    type: language-dropdown
    enabled: true

footer:
  enabled: false

geocoder:
  maxNearbyStops: 6
  maxResults: 20
  #################
  ## HERE.COM
  type: HERE
  api:
   autocomplete: https://autosuggest.search.hereapi.com/v1/autosuggest
  apiKey: "${HERE_APIKEY}"
  #################
  ## GEOCODE.EARTH
  # type: PELIAS
  # baseUrl: https://api.geocode.earth
  # apiKey: "${PELIAS_APIKEY}"
  patchList:
    PELIAS:
      "1125787603": #madonna campiglio
        lon: 10.8262567
        lat: 46.2319871
      "1126005653": #mavignola
        lon: 10.78496
        lat: 46.18978

  boundary:
    rect:
      minLon: 10.470121
      maxLon: 12.255011
      minLat: 46.188280
      maxLat: 47.088780
      #Suedtirol 10.470121,46.188280,12.255011,47.088780
  # layers: #filter requested layers for pelias geocoder
  # - venue
  # - street
  # - address
  # - borough
  # attribution: 'attribution_geocode_earth'
  #  focusPoint:
  #   lat: 46.229372
  #   lon: 10.826636
  # tenant_pois: #tenant specific array of pois that appear in the search dropdown
  # - name: "poi 2"
  #   lat: 46.218776
  #   lon: 10.82389
  #   type: "custom"
  # - name: "poi 3"
  #   lat: 46.21376
  #   lon: 10.82189
  #   type: "custom"
  # - name: "poi 4"
  #   lat: 46.2196
  #   lon: 10.82189
  #   type: "custom"

language:
  storageDisclaimer: storage_disclaimer
  routeViewer: route_viewer
  routeViewerDetails: route_view_details
  defaultLanguage: it
  fallbackLanguage: en
  langList:
    - lang: "it"
      label: Italiano
    - lang: "en"
      label: English
    - lang: "de"
      label: Deutsch

  #SET HERE DEFAULT FRONT-END LANGUAGE

# react-router config, for URL routing (not to be confused with multimodal/OTP routing)
#reactRouter:
#   # If app is to be deployed to a URL subdirectory (e.g. http://foo.bar/app), specify the path here:
#  basename: ${FOLDER}

# Enabled multimodal routing types (e.g. interary, profile)
routingTypes:
  - key: ITINERARY
    text: exact_time

  # Delete/uncomment the following block to disable profile routing
  #- key: PROFILE
  #  text: Time Window
  #  api: # Specifies a different API endpoint for profile routing
  #    host: https://otp.openmove.com/router/car
  #    path: /api

# Show/hide elevation profile chart for walk/bike legs
elevationProfile: true

# Provide a list of operators to enhance the user experience for multi-agency
# implementations. The order of the agencies will dictate the order that routes
# appear in the route viewer. Also, optionally provide operator logos to appear
# in narrative itinerary (matched on agency_id). Note: these logos will
# override the values found in agency.txt#agency_branding_url.
transitOperators:
  - id: "12"
    logo: https://openmove.s3.eu-west-1.amazonaws.com/logos/logo_tt_testo_blu.png
  - id: "1"
    logo: https://www.suedtirolmobil.info/typo3conf/ext/sta_layout/Resources/Public/Images/logo.svg
  - id: "Easymobil"
    logo: https://www.easymobil.it/wp-content/themes/easy_mobil/images/logo.png

persistence:
  enabled: true
  strategy: localStorage

# Map config
map:
  views:
    - type: DEFAULT
      text: Mappa
    # Delete/uncomment the following block to disable the stylized map
    #- type: STYLIZED
    #  text: Network View

  # Default map center
  initLat: 46.670953
  initLon: 11.155007
  initZoom: 15
  # closer-in zoom levels don't have any tiles that could be rendered by
  maxZoom: 18
  # Base layers for default map
  controls:
    overlays:
      collapsed: true
      closeBtn: true
  baseLayers:
    - name: Streets
      url: //cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}@2x.png
      subdomains: 'abcd'
      attribution: attribution_street
      hasRetinaSupport: true
    - name: Printer
      url: //stamen-tiles-{s}.a.ssl.fastly.net/toner-lite/{z}/{x}/{y}.png
      attribution: attribution_printer
    - name: Openstreetmap
      url: //{s}.tile.osm.org/{z}/{x}/{y}.png
      attribution: attribution_osm

  overlays:
    - type: stops
      name: stops
      enabled: true
      visible: true
      iconWidth: 15
      iconHeight: 15
      iconMarkerColor: "#095980"
      iconColor: "#fff"
      minZoom: 15
      parentStations: true
      minZoomStation: 17
      #startCenter: [46.234763, 11.001591]
      #startBBox: 0
      #filters: "/static/filters/stops_trentino.json"
    - type: bike-rental
      name: bikesharing
      # enabled: true
      # visible: false
      # markerCluster: true
      modes:
        - BICYCLE_RENT
      companies:
        #TODO move to filters server side
        - BZ
        - ME
        - PAPIN
      iconWidth: 42
      #startCenter: [46.234763, 11.001591]
      #startBBox: 0
      iconHeight: 50
      iconMarkerColor: "#ead896"
      iconColor: "#5d5d5d"
      ###only roadtraffic
      #filters: ${OTPCONFIG_BASEURL}/otpconfig/bikerental/filters.json
      filters: "/static/filters/bikerental.json"

    - type: car-rental
      name: carsharing
      # enabled: true
      # visible: false
      # markerCluster: true
      modes:
        - CAR_RENT
      companies:
        - SUEDTIROL
      api: ${CARSHARING_BASEURL}/carsharing/stations.json
      iconWidth: 42
      iconHeight: 50
      iconMarkerColor: "#d9bd48"
      iconColor: "#5d5d5d"
      #startCenter: [46.234763, 11.001591]
      #startBBox: 0
      ##dinamic filters
      ##filters: ${CARSHARING_BASEURL}/carsharing/filters.json
      filters: "/static/filters/carsharing.json"
      # filtersCustom:
      #   enabled: true

    - type: charger
      name: charger
      # enabled: true
      # visible: false
      # markerCluster: true
      api: ${CHARGER_BASEURL}/charger/stations.json
      iconWidth: 42
      iconHeight: 50
      iconMarkerColor: "#FAA61F"
      iconColor: "#5d5d5d"
      #startCenter: [46.234763, 11.001591]
      #startBBox: 0
      #dinamic filters
      ##filters: ${CHARGER_BASEURL}/charger/filters.json
      filters: "/static/filters/charger.json"

    - type: parking
      name: parking # name is used as an identifier keep it unique per overlay type
      # enabled: true
      # visible: false
      # markerCluster: true
      api: ${PARKING_BASEURL}/parking/all.json
      iconWidth: 42
      iconHeight: 50
      iconMarkerColor: "#b0d1ef"
      iconColor: "#5d5d5d"
      #startCenter: [46.234763, 11.001591]
      #startBBox: 0
      ##dinamic filters
      ##filters: ${PARKING_BASEURL}/parking/filters.json
      filters: "/static/filters/parking.json"
      pollingUpdate: true
      updateBBox: true

    - type: drt
      name: ondemand
      # enabled: true
      # visible: false
      api: ${DRT_BASEURL}/drt/all.json
      pollingInterval: 5000
      #startCenter: [46.234763, 11.001591]
      #startBBox: 0
      iconWidth: 15
      iconHeight: 15
      iconMarkerColor: "#095980"
      iconVehicleColor: "#095980"
      iconColor: "#fff"
      pathColor: "#3388ff"
      pathDash: 1,1
      areas:
        1:
          name: 'Area Esterna'
          color: 'red'
        2:
          name: 'Area Principale'
          color: 'green'
        3:
          name: 'Area Esterna'
          color: 'red'

    - type: traffic
      name: traffic
      # enabled: true
      # visible: false
      # markerCluster: true
      api: ${TRAFFIC_BASEURL}/traffic/linkstations.json
      pollingInterval: 5000
      levelColors:
        - '#aab'  #not measured
        - '#3d0'  #green
        - '#ed0'  #yellow
        - '#e00'  #red
      #startCenter: [46.234763, 11.001591]
      #startBBox: 0

    - type: webcam
      name: webcam
      enabled: false
      # markerCluster: true
      # visible: false
      api: ${WEBCAM_BASEURL}/webcam/stations.json
      iconWidth: 42
      iconHeight: 50
      iconMarkerColor: "#B62923"
      iconColor: "#B73833"
      ##dinamic filters
      ##filters: ${PARKING_BASEURL}/parking/filters.json
      filters: "/static/filters/webcam.json"

    - type: vms
      name: vms
      enabled: false
      # visible: false
      # markerCluster: true
      api: http://192.168.1.41:8080/old.json
      iconWidth: 42
      iconHeight: 50
      iconMarkerColor: "#B62923"
      iconColor: "#B73833"

# Mode selector configuration
# http://otp-docs.ibi-transit.com/Configuration/
modes:
  transitModes:
    ##for each mode can be added `showWheelchairSetting: true`
    - mode: BUS
      label: bus
    - mode: RAIL
      label: train
    - mode: GONDOLA
      label: funivia
    # - mode: FUNICULAR
    #   label: funicular
    # - mode: CABLE_CAR
    #   label: cable_car
    # - mode: TRAM
    #   label: tram
    # - mode: METRO
    #   label: metro
    # - mode: FERRY
    #   label: ferry
  accessModes:
    - mode: BICYCLE
      label: bike_ride
    - mode: BICYCLE_RENT
      label: bikesharing_ride
    - mode: CAR_PARK
      label: park_ride
    - mode: CAR_RENT
      label: carsharing_ride
    - mode: MICROMOBILITY
      label: micromobility_ride
    # - mode: MICROMOBILITY_RENT
    #   label: Transit + E-scooter

  # which exclusive modes to show. This involves using a single mode and no
  # transit for the duration of the trip. Further configurations of
  # `bicycleModes`, `micromobilityModes` and/or `carModes` are needed as
  # desired, but no extra configuration is needed for a WALK exclusive mode.
  exclusiveModes:
    - WALK
    - BICYCLE
    - MICROMOBILITY

  bicycleModes:
    - mode: BICYCLE
      label: my_bike
      iconWidth: 18
    - mode: BICYCLE_RENT
      label: bikesharing
      iconWidth: 36

# A list of private transportation operators. These are either companies that
# provide rental vehicles or transportation network companies. Companies that
# have multiple modes of transport should have all modes listed as a string with
# commas. For example: BICYCLE_RENT,MICROMOBILITY_RENT.
companies:
    - id: BZ
      label: bikesharing_bz
      modes: BICYCLE_RENT

    - id: ME
      label: bikesharing_mr
      modes: BICYCLE_RENT

    - id: PAPIN
      label: bikerental_papi
      modes: BICYCLE_RENT

    - id: CAR2GO
      label: carsharing_car2go
      modes: CAR_RENT
location:
  iconColor: "#000033"
errorMessages:
  - id: 404
    msg: msg_404
  - id: 405
    msg: msg_404
  - id: 480
    msg: msg_404

dateTime:
  timeFormat: HH:mm
  dateFormat: DD/MM/YYYY
  longDateFormat: D MMMM YYYY
itinerary:
  showRouteFares: true
trip:
  showFares: true
  style:
    color: "#000033"
    opacity: 0.6
    weight: 8
transit:
  style:
    fill: '#000033'
    stroke: '#000033'
    stroke_width: 6
    background: '#000033'
    places:
      fill:
        bikeshare_station: "#f00"
        car_walk_transition: "#888"
        e_scooter_station: "#f5a729"
        default: "null"
      stroke: "#fff"
      stroke_width: 2
      radius: 7
    modes:
      bicycle:
        color: "#8f99c2"
      bus:
         color: "#000033"
      car:
         color: "#336699"
      park:
         color: "#E4CCCC" #todo
      rail:
         color: "#000033"
      gondola:
        color: "#CAC3DF"
      walk:
         color: "#A89968"
      default:
        color: "#333333"
    stops_merged:
      radius: 6
      stroke: "#000033"

# modes:
#   WALK: "#87cefa"
#   BICYCLE: "red"
#   SUBWAY: "#f00"
#   RAIL: "#095980"
#   BUS: "#095980"
#   TRAM: "#800"
#   FERRY: "#095980"
#   CAR: "#444"
#   MICROMOBILITY: "#f5a729"
