#
# Require a .env file contains all environment vars
# look contents of file _dot.env.example
#
version: '3'

networks:
  default:
    driver: bridge

services:
  journey:
    container_name: journey
    ports:
      - "8081:80"
    image: journey:latest
    build:
      context: ./
      dockerfile: docker/Dockerfile
      args:
        JOURNEY_THEME: $JOURNEY_THEME
        API_HOST: $API_HOST
        API_PATH: $API_PATH
        API_PORT: $API_PORT
        CARSHARING_BASEURL: $CARSHARING_BASEURL
        CHARGER_BASEURL: $CHARGER_BASEURL
        DRT_BASEURL: $DRT_BASEURL
        GEOCODER_BASEURL: $GEOCODER_BASEURL
        PARKING_BASEURL: $PARKING_BASEURL
        TRAFFIC_BASEURL: $TRAFFIC_BASEURL
        #WEBCAM_BASEURL: $WEBCAM_BASEURL
        ##
        ## debug of remote instance
        #API_HOST: https://otp.opendatahub.testingmachine.eu
        #API_PORT: 443
        #API_PATH: /otp/routers/openmove
        #GEOCODER_BASEURL: https://geocoder.otp.opendatahub.testingmachine.eu/v1
        #PARKING_BASEURL: https://parking.otp.opendatahub.testingmachine.eu
        #DRT_BASEURL:  https://drt.otp.opendatahub.testingmachine.eu
        #CHARGER_BASEURL: https://charger.otp.opendatahub.testingmachine.eu
        #CARSHARING_BASEURL: https://carsharing.otp.opendatahub.testingmachine.eu
        #TRAFFIC_BASEURL: https://traffic.otp.opendatahub.testingmachine.eu
        ##
        #GOOGLE_ANALYTICS_ID: $GOOGLE_ANALYTICS_ID

  # datatest:
  #   container_name: datatest
  #   ports:
  #     - "7000:7000"
  #   image: datatest:latest
  #   build:
  #     context: journey/tests/
  #     #dockerfile: journey/tests/Dockerfile
  #   restart: "no"
