version: '3.1.0'
theme: 'red'
staticBaseUrl: '${STATIC_BASEURL}'
api:
  host: https://dev-tripplanner.openmove.com
  path: /otp/routers/trentino
  port: 443
configByTheme:
  red:
    map:
      overlays:
        - name: drt
          enabled: false
        - name: webcam
          enabled: true
        - name: vms
          enabled: true
    footer:
      enabled: true
      navList:
        - name: acessibility
          enabled: true
          type: link
          linkUrl : ""
        - name: legals
          enabled: true
          type: link
          linkUrl : ""
        - name: credits
          enabled: true
          type: link-modal
          htmlUrl: "/static/credits.html"
        - name: privacy policy
          enabled: true
          type: link
          linkUrl : ""
        - name: meteo
          enabled: true
          type: link
          linkUrl : ""
branding: "Merano - Alto Adige/Suedtirol"
title: "Merano - Alto Adige/Suedtirol"
brandNavbar: Merano
brandNavbarLogo: null
brandByDomain:
  localhost:
    branding: Journey
    title: Journey
    brandNavbar: Journey
    brandNavbarLogo: openmove
  mobility.meran.eu:
    branding: Merano - Alto Adige/Suedtirol
    title: Merano - Alto Adige/Suedtirol
    brandNavbar: ''
    brandNavbarLogo: merano
  mobility.merano.eu:
    branding: Merano - Alto Adige/Suedtirol
    title: Merano - Alto Adige/Suedtirol
    brandNavbar: ''
    brandNavbarLogo: merano
  mobility.bz.it:
    branding: Bolzano - Alto Adige/Suedtirol
    title: Bolzano - Alto Adige/Suedtirol
    brandNavbar: ''
    brandNavbarLogo: bolzano
  journey.opendatahub.bz.it:
    branding: Mentor
    title: Mentor
    brandNavbar: ''
    brandNavbarLogo: interreg
  journey.opendatahub.com:
    branding: Mentor
    title: Mentor
    brandNavbar: ''
    brandNavbarLogo: interreg
configByDomain:
  mobility.meran.eu:
    map:
      initLat: 46.6709
      initLon: 11.1550
      initZoom: 15
  mobility.bz.it:
    map:
      initLat: 46.4921
      initLon: 11.3333
      initZoom: 15
reportIssue:
  mailto: support@openmove.com
analytics:
  matomo:
    baseUrl: ${MATOMO_BASE_URL}
    siteId: ${MATOMO_SITE_ID}
header:
  enabled: true
  navList:
  - name: ""
    type: nav-item
    enabled: true
    icon: "location-arrow"
    onClickEvent: setGpsLocation
  - name: route_viewer
    type: nav-item
    enabled: true
    icon: "bus"
    onClickEvent: showRouteViewer
  - name: restart
    type: nav-item
    enabled: true
    icon: "undo"
    onClickEvent: startOver
  - name: credits
    type: nav-modal
    htmlUrl: "/static/credits.html"
    enabled: true
    icon: "info-circle"
  - name: language-dropdown
    type: language-dropdown
    enabled: true
footer:
  enabled: false
geocoder:
  baseUrl: https://geocoder.otp.opendatahub.testingmachine.eu
  maxNearbyStops: 6
  maxResults: 20
  apiKey: ""
  api:
    autocomplete: 'https://autosuggest.search.hereapi.com/v1/autosuggest'
  type: HERE
  boundary:
    rect:
      minLon: 10.470121
      maxLon: 12.255011
      minLat: 46.188280
      maxLat: 47.088780
language:
  storageDisclaimer: storage_disclaimer
  routeViewer: route_viewer
  routeViewerDetails: route_view_details
  defaultLanguage: it
  fallbackLanguage: en
  langList:
    - lang: "it"
      label: Italiano
    - lang: "en"
      label: English
    - lang: "de"
      label: Deutsch
routingTypes:
  - key: ITINERARY
    text: exact_time
elevationProfile: true
transitOperators:
  - id: "12"
    logo: https://openmove.s3.eu-west-1.amazonaws.com/logos/logo_tt_testo_blu.png
  - id: "1"
    logo: https://www.suedtirolmobil.info/typo3conf/ext/sta_layout/Resources/Public/Images/logo.svg
  - id: "Easymobil"
    logo: https://www.easymobil.it/wp-content/themes/easy_mobil/images/logo.png
persistence:
  enabled: true
  strategy: localStorage
map:
  views:
    - type: DEFAULT
      text: Mappa
  initLat: 46.670953
  initLon: 11.155007
  initZoom: 15
  maxZoom: 18
  controls:
    overlays:
      collapsed: true
      closeBtn: true
  baseLayers:
    - name: Streets
      url: //cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}@2x.png
      subdomains: 'abcd'
      attribution: attribution_street
      hasRetinaSupport: true
    - name: Printer
      url: //stamen-tiles-{s}.a.ssl.fastly.net/toner-lite/{z}/{x}/{y}.png
      attribution: attribution_printer
    - name: Openstreetmap
      url: //{s}.tile.osm.org/{z}/{x}/{y}.png
      attribution: attribution_osm
  overlays:
    - type: stops
      name: stops
      enabled: true
      visible: true
      iconWidth: 15
      iconHeight: 15
      iconMarkerColor: "#095980"
      iconColor: "#fff"
      minZoom: 15
      parentStations: true
      minZoomStation: 17
    - type: bike-rental
      name: bikesharing
      modes:
        - BICYCLE_RENT
      companies:
        - BZ
        - ME
        - PAPIN
      iconWidth: 42
      iconHeight: 50
      iconMarkerColor: "#ead896"
      iconColor: "#5d5d5d"
      filters: "/static/filters/bikerental.json"
    - type: car-rental
      name: carsharing
      modes:
        - CAR_RENT
      companies:
        - SUEDTIROL
      api: https://carsharing.otp.opendatahub.testingmachine.eu/carsharing/stations.json
      iconWidth: 42
      iconHeight: 50
      iconMarkerColor: "#d9bd48"
      iconColor: "#5d5d5d"
      filters: "/static/filters/carsharing.json"
    - type: charger
      name: charger
      api: https://test-road-traffic.openmove.com/charger/stations.json
      iconWidth: 42
      iconHeight: 50
      iconMarkerColor: "#FAA61F"
      iconColor: "#5d5d5d"
      filters: "/static/filters/charger.json"
    - type: parking
      name: parking2
      api: https://test-road-traffic.openmove.com/parking/all.json
      iconWidth: 42
      iconHeight: 50
      iconMarkerColor: "#b0d1ef"
      iconColor: "#5d5d5d"
      filters: "/static/filters/parking.json"
      pollingUpdate: true
      updateBBox: true
    - type: parking
      name: parking1
      api: https://parking.otp.opendatahub.bz.it/parking/all.json
      iconWidth: 21
      iconHeight: 25
      iconMarkerColor: "#333"
      iconColor: "#000"
      filters: "/static/filters/parking.json"
      pollingUpdate: false
      updateBBox: false
    - type: drt
      name: ondemand
      api: https://parking.otp.opendatahub.bz.it/parking/stations.json
      pollingInterval: 5000
      iconWidth: 15
      iconHeight: 15
      iconMarkerColor: "#095980"
      iconVehicleColor: "#095980"
      iconColor: "#fff"
      pathColor: "#3388ff"
      pathDash: 1,1
      areas:
        1:
          name: 'Area Esterna'
          color: 'red'
        2:
          name: 'Area Principale'
          color: 'green'
        3:
          name: 'Area Esterna'
          color: 'red'
    - type: traffic
      name: traffic
      api: https://test-road-traffic.openmove.com/traffic/linkstations.json
      pollingInterval: 5000
      levelColors:
        - '#aab'  #not measured
        - '#3d0'  #green
        - '#ed0'  #yellow
        - '#e00'  #red
    - type: webcam
      name: webcam
      enabled: false
      api: https://test-road-traffic.openmove.com/webcam/stations.json
      iconWidth: 42
      iconHeight: 50
      iconMarkerColor: "#B62923"
      iconColor: "#B73833"
      filters: "/static/filters/webcam.json"
    - type: vms
      name: vms
      enabled: false
      api: http://192.168.1.41:8080/old.json
      iconWidth: 42
      iconHeight: 50
      iconMarkerColor: "#B62923"
      iconColor: "#B73833"
modes:
  transitModes:
    - mode: BUS
      label: bus
    - mode: RAIL
      label: train
    - mode: GONDOLA
      label: funivia
  accessModes:
    - mode: BICYCLE
      label: bike_ride
    - mode: BICYCLE_RENT
      label: bikesharing_ride
    - mode: CAR_PARK
      label: park_ride
    - mode: CAR_RENT
      label: carsharing_ride
    - mode: MICROMOBILITY
      label: micromobility_ride
  exclusiveModes:
    - WALK
    - BICYCLE
    - MICROMOBILITY
  bicycleModes:
    - mode: BICYCLE
      label: my_bike
      iconWidth: 18
    - mode: BICYCLE_RENT
      label: bikesharing
      iconWidth: 36
companies:
    - id: BZ
      label: bikesharing_bz
      modes: BICYCLE_RENT
    - id: ME
      label: bikesharing_mr
      modes: BICYCLE_RENT
    - id: PAPIN
      label: bikerental_papi
      modes: BICYCLE_RENT
    - id: CAR2GO
      label: carsharing_car2go
      modes: CAR_RENT
errorMessages:
  - id: 404
    msg: msg_404
  - id: 405
    msg: msg_404
  - id: 480
    msg: msg_404
dateTime:
  timeFormat: HH:mm
  dateFormat: DD/MM/YYYY
  longDateFormat: D MMMM YYYY
itinerary:
  showRouteFares: true
trip:
  style:
    color: "#095980"
    opacity: 0.6
    weight: 8
transit:
  style:
    fill: '#095980'
    stroke: '#095980'
    stroke_width: 6
    background: '#095980'
    places:
      fill:
        bikeshare_station: "#f00"
        car_walk_transition: "#888"
        e_scooter_station: "#f5a729"
        default: "null"
      stroke: "#fff"
      stroke_width: 2
      radius: 7
    modes:
      bicycle:
        color: "#E0C3E2"
      bus:
         color: "#CAC3DF"
      car:
         color: "#E4CCCC"
      park:
         color: "#E4CCCC"
      rail:
         color: "#BDDAC0"
      walk:
         color: "#DFC486"
      default:
        color: "#333333"
    stops_merged:
      radius: 6
      stroke: "#095980"
